/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProtocolosIatfIndexRouteImport } from './routes/_app.protocolos-iatf.index'
import { Route as AppPartosIndexRouteImport } from './routes/_app.partos.index'
import { Route as AppMatrizesIndexRouteImport } from './routes/_app.matrizes.index'
import { Route as AppDescartesIndexRouteImport } from './routes/_app.descartes.index'
import { Route as AppProtocolosIatfNovoRouteImport } from './routes/_app.protocolos-iatf.novo'
import { Route as AppProtocolosIatfIdRouteImport } from './routes/_app.protocolos-iatf.$id'
import { Route as AppPartosNovoRouteImport } from './routes/_app.partos.novo'
import { Route as AppMatrizesIdRouteImport } from './routes/_app.matrizes.$id'
import { Route as AppDescartesNovoRouteImport } from './routes/_app.descartes.novo'
import { Route as AppPartosIdIndexRouteImport } from './routes/_app.partos.$id.index'
import { Route as AppDescartesIdIndexRouteImport } from './routes/_app.descartes.$id.index'
import { Route as AppPartosIdEditarRouteImport } from './routes/_app.partos.$id.editar'
import { Route as AppDescartesIdEditarRouteImport } from './routes/_app.descartes.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolosIatfIndexRoute = AppProtocolosIatfIndexRouteImport.update({
  id: '/protocolos-iatf/',
  path: '/protocolos-iatf/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosIndexRoute = AppPartosIndexRouteImport.update({
  id: '/partos/',
  path: '/partos/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrizesIndexRoute = AppMatrizesIndexRouteImport.update({
  id: '/matrizes/',
  path: '/matrizes/',
  getParentRoute: () => AppRoute,
} as any)
const AppDescartesIndexRoute = AppDescartesIndexRouteImport.update({
  id: '/descartes/',
  path: '/descartes/',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolosIatfNovoRoute = AppProtocolosIatfNovoRouteImport.update({
  id: '/protocolos-iatf/novo',
  path: '/protocolos-iatf/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolosIatfIdRoute = AppProtocolosIatfIdRouteImport.update({
  id: '/protocolos-iatf/$id',
  path: '/protocolos-iatf/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosNovoRoute = AppPartosNovoRouteImport.update({
  id: '/partos/novo',
  path: '/partos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrizesIdRoute = AppMatrizesIdRouteImport.update({
  id: '/matrizes/$id',
  path: '/matrizes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDescartesNovoRoute = AppDescartesNovoRouteImport.update({
  id: '/descartes/novo',
  path: '/descartes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosIdIndexRoute = AppPartosIdIndexRouteImport.update({
  id: '/partos/$id/',
  path: '/partos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppDescartesIdIndexRoute = AppDescartesIdIndexRouteImport.update({
  id: '/descartes/$id/',
  path: '/descartes/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosIdEditarRoute = AppPartosIdEditarRouteImport.update({
  id: '/partos/$id/editar',
  path: '/partos/$id/editar',
  getParentRoute: () => AppRoute,
} as any)
const AppDescartesIdEditarRoute = AppDescartesIdEditarRouteImport.update({
  id: '/descartes/$id/editar',
  path: '/descartes/$id/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/descartes/novo': typeof AppDescartesNovoRoute
  '/matrizes/$id': typeof AppMatrizesIdRoute
  '/partos/novo': typeof AppPartosNovoRoute
  '/protocolos-iatf/$id': typeof AppProtocolosIatfIdRoute
  '/protocolos-iatf/novo': typeof AppProtocolosIatfNovoRoute
  '/descartes/': typeof AppDescartesIndexRoute
  '/matrizes/': typeof AppMatrizesIndexRoute
  '/partos/': typeof AppPartosIndexRoute
  '/protocolos-iatf/': typeof AppProtocolosIatfIndexRoute
  '/descartes/$id/editar': typeof AppDescartesIdEditarRoute
  '/partos/$id/editar': typeof AppPartosIdEditarRoute
  '/descartes/$id/': typeof AppDescartesIdIndexRoute
  '/partos/$id/': typeof AppPartosIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
  '/descartes/novo': typeof AppDescartesNovoRoute
  '/matrizes/$id': typeof AppMatrizesIdRoute
  '/partos/novo': typeof AppPartosNovoRoute
  '/protocolos-iatf/$id': typeof AppProtocolosIatfIdRoute
  '/protocolos-iatf/novo': typeof AppProtocolosIatfNovoRoute
  '/descartes': typeof AppDescartesIndexRoute
  '/matrizes': typeof AppMatrizesIndexRoute
  '/partos': typeof AppPartosIndexRoute
  '/protocolos-iatf': typeof AppProtocolosIatfIndexRoute
  '/descartes/$id/editar': typeof AppDescartesIdEditarRoute
  '/partos/$id/editar': typeof AppPartosIdEditarRoute
  '/descartes/$id': typeof AppDescartesIdIndexRoute
  '/partos/$id': typeof AppPartosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/descartes/novo': typeof AppDescartesNovoRoute
  '/_app/matrizes/$id': typeof AppMatrizesIdRoute
  '/_app/partos/novo': typeof AppPartosNovoRoute
  '/_app/protocolos-iatf/$id': typeof AppProtocolosIatfIdRoute
  '/_app/protocolos-iatf/novo': typeof AppProtocolosIatfNovoRoute
  '/_app/descartes/': typeof AppDescartesIndexRoute
  '/_app/matrizes/': typeof AppMatrizesIndexRoute
  '/_app/partos/': typeof AppPartosIndexRoute
  '/_app/protocolos-iatf/': typeof AppProtocolosIatfIndexRoute
  '/_app/descartes/$id/editar': typeof AppDescartesIdEditarRoute
  '/_app/partos/$id/editar': typeof AppPartosIdEditarRoute
  '/_app/descartes/$id/': typeof AppDescartesIdIndexRoute
  '/_app/partos/$id/': typeof AppPartosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/relatorios'
    | '/descartes/novo'
    | '/matrizes/$id'
    | '/partos/novo'
    | '/protocolos-iatf/$id'
    | '/protocolos-iatf/novo'
    | '/descartes/'
    | '/matrizes/'
    | '/partos/'
    | '/protocolos-iatf/'
    | '/descartes/$id/editar'
    | '/partos/$id/editar'
    | '/descartes/$id/'
    | '/partos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/relatorios'
    | '/'
    | '/descartes/novo'
    | '/matrizes/$id'
    | '/partos/novo'
    | '/protocolos-iatf/$id'
    | '/protocolos-iatf/novo'
    | '/descartes'
    | '/matrizes'
    | '/partos'
    | '/protocolos-iatf'
    | '/descartes/$id/editar'
    | '/partos/$id/editar'
    | '/descartes/$id'
    | '/partos/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/relatorios'
    | '/_app/'
    | '/_app/descartes/novo'
    | '/_app/matrizes/$id'
    | '/_app/partos/novo'
    | '/_app/protocolos-iatf/$id'
    | '/_app/protocolos-iatf/novo'
    | '/_app/descartes/'
    | '/_app/matrizes/'
    | '/_app/partos/'
    | '/_app/protocolos-iatf/'
    | '/_app/descartes/$id/editar'
    | '/_app/partos/$id/editar'
    | '/_app/descartes/$id/'
    | '/_app/partos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolos-iatf/': {
      id: '/_app/protocolos-iatf/'
      path: '/protocolos-iatf'
      fullPath: '/protocolos-iatf/'
      preLoaderRoute: typeof AppProtocolosIatfIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/': {
      id: '/_app/partos/'
      path: '/partos'
      fullPath: '/partos/'
      preLoaderRoute: typeof AppPartosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matrizes/': {
      id: '/_app/matrizes/'
      path: '/matrizes'
      fullPath: '/matrizes/'
      preLoaderRoute: typeof AppMatrizesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/descartes/': {
      id: '/_app/descartes/'
      path: '/descartes'
      fullPath: '/descartes/'
      preLoaderRoute: typeof AppDescartesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolos-iatf/novo': {
      id: '/_app/protocolos-iatf/novo'
      path: '/protocolos-iatf/novo'
      fullPath: '/protocolos-iatf/novo'
      preLoaderRoute: typeof AppProtocolosIatfNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolos-iatf/$id': {
      id: '/_app/protocolos-iatf/$id'
      path: '/protocolos-iatf/$id'
      fullPath: '/protocolos-iatf/$id'
      preLoaderRoute: typeof AppProtocolosIatfIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/novo': {
      id: '/_app/partos/novo'
      path: '/partos/novo'
      fullPath: '/partos/novo'
      preLoaderRoute: typeof AppPartosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matrizes/$id': {
      id: '/_app/matrizes/$id'
      path: '/matrizes/$id'
      fullPath: '/matrizes/$id'
      preLoaderRoute: typeof AppMatrizesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/descartes/novo': {
      id: '/_app/descartes/novo'
      path: '/descartes/novo'
      fullPath: '/descartes/novo'
      preLoaderRoute: typeof AppDescartesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/$id/': {
      id: '/_app/partos/$id/'
      path: '/partos/$id'
      fullPath: '/partos/$id/'
      preLoaderRoute: typeof AppPartosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/descartes/$id/': {
      id: '/_app/descartes/$id/'
      path: '/descartes/$id'
      fullPath: '/descartes/$id/'
      preLoaderRoute: typeof AppDescartesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/$id/editar': {
      id: '/_app/partos/$id/editar'
      path: '/partos/$id/editar'
      fullPath: '/partos/$id/editar'
      preLoaderRoute: typeof AppPartosIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/descartes/$id/editar': {
      id: '/_app/descartes/$id/editar'
      path: '/descartes/$id/editar'
      fullPath: '/descartes/$id/editar'
      preLoaderRoute: typeof AppDescartesIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDescartesNovoRoute: typeof AppDescartesNovoRoute
  AppMatrizesIdRoute: typeof AppMatrizesIdRoute
  AppPartosNovoRoute: typeof AppPartosNovoRoute
  AppProtocolosIatfIdRoute: typeof AppProtocolosIatfIdRoute
  AppProtocolosIatfNovoRoute: typeof AppProtocolosIatfNovoRoute
  AppDescartesIndexRoute: typeof AppDescartesIndexRoute
  AppMatrizesIndexRoute: typeof AppMatrizesIndexRoute
  AppPartosIndexRoute: typeof AppPartosIndexRoute
  AppProtocolosIatfIndexRoute: typeof AppProtocolosIatfIndexRoute
  AppDescartesIdEditarRoute: typeof AppDescartesIdEditarRoute
  AppPartosIdEditarRoute: typeof AppPartosIdEditarRoute
  AppDescartesIdIndexRoute: typeof AppDescartesIdIndexRoute
  AppPartosIdIndexRoute: typeof AppPartosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppDescartesNovoRoute: AppDescartesNovoRoute,
  AppMatrizesIdRoute: AppMatrizesIdRoute,
  AppPartosNovoRoute: AppPartosNovoRoute,
  AppProtocolosIatfIdRoute: AppProtocolosIatfIdRoute,
  AppProtocolosIatfNovoRoute: AppProtocolosIatfNovoRoute,
  AppDescartesIndexRoute: AppDescartesIndexRoute,
  AppMatrizesIndexRoute: AppMatrizesIndexRoute,
  AppPartosIndexRoute: AppPartosIndexRoute,
  AppProtocolosIatfIndexRoute: AppProtocolosIatfIndexRoute,
  AppDescartesIdEditarRoute: AppDescartesIdEditarRoute,
  AppPartosIdEditarRoute: AppPartosIdEditarRoute,
  AppDescartesIdIndexRoute: AppDescartesIdIndexRoute,
  AppPartosIdIndexRoute: AppPartosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
