/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProtocolosRouteImport } from './routes/_app.protocolos'
import { Route as AppPrenhezesRouteImport } from './routes/_app.prenhezes'
import { Route as AppEstacoesRouteImport } from './routes/_app.estacoes'
import { Route as AppDescartesRouteImport } from './routes/_app.descartes'
import { Route as AppPartosIndexRouteImport } from './routes/_app.partos.index'
import { Route as AppMatrizesIndexRouteImport } from './routes/_app.matrizes.index'
import { Route as AppPartosNovoRouteImport } from './routes/_app.partos.novo'
import { Route as AppMatrizesIdRouteImport } from './routes/_app.matrizes.$id'
import { Route as AppPartosIdIndexRouteImport } from './routes/_app.partos.$id.index'
import { Route as AppPartosIdEditarRouteImport } from './routes/_app.partos.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolosRoute = AppProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => AppRoute,
} as any)
const AppPrenhezesRoute = AppPrenhezesRouteImport.update({
  id: '/prenhezes',
  path: '/prenhezes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstacoesRoute = AppEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDescartesRoute = AppDescartesRouteImport.update({
  id: '/descartes',
  path: '/descartes',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosIndexRoute = AppPartosIndexRouteImport.update({
  id: '/partos/',
  path: '/partos/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrizesIndexRoute = AppMatrizesIndexRouteImport.update({
  id: '/matrizes/',
  path: '/matrizes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosNovoRoute = AppPartosNovoRouteImport.update({
  id: '/partos/novo',
  path: '/partos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrizesIdRoute = AppMatrizesIdRouteImport.update({
  id: '/matrizes/$id',
  path: '/matrizes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosIdIndexRoute = AppPartosIdIndexRouteImport.update({
  id: '/partos/$id/',
  path: '/partos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartosIdEditarRoute = AppPartosIdEditarRouteImport.update({
  id: '/partos/$id/editar',
  path: '/partos/$id/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/descartes': typeof AppDescartesRoute
  '/estacoes': typeof AppEstacoesRoute
  '/prenhezes': typeof AppPrenhezesRoute
  '/protocolos': typeof AppProtocolosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/matrizes/$id': typeof AppMatrizesIdRoute
  '/partos/novo': typeof AppPartosNovoRoute
  '/matrizes/': typeof AppMatrizesIndexRoute
  '/partos/': typeof AppPartosIndexRoute
  '/partos/$id/editar': typeof AppPartosIdEditarRoute
  '/partos/$id/': typeof AppPartosIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/descartes': typeof AppDescartesRoute
  '/estacoes': typeof AppEstacoesRoute
  '/prenhezes': typeof AppPrenhezesRoute
  '/protocolos': typeof AppProtocolosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
  '/matrizes/$id': typeof AppMatrizesIdRoute
  '/partos/novo': typeof AppPartosNovoRoute
  '/matrizes': typeof AppMatrizesIndexRoute
  '/partos': typeof AppPartosIndexRoute
  '/partos/$id/editar': typeof AppPartosIdEditarRoute
  '/partos/$id': typeof AppPartosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/descartes': typeof AppDescartesRoute
  '/_app/estacoes': typeof AppEstacoesRoute
  '/_app/prenhezes': typeof AppPrenhezesRoute
  '/_app/protocolos': typeof AppProtocolosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/matrizes/$id': typeof AppMatrizesIdRoute
  '/_app/partos/novo': typeof AppPartosNovoRoute
  '/_app/matrizes/': typeof AppMatrizesIndexRoute
  '/_app/partos/': typeof AppPartosIndexRoute
  '/_app/partos/$id/editar': typeof AppPartosIdEditarRoute
  '/_app/partos/$id/': typeof AppPartosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/descartes'
    | '/estacoes'
    | '/prenhezes'
    | '/protocolos'
    | '/relatorios'
    | '/matrizes/$id'
    | '/partos/novo'
    | '/matrizes/'
    | '/partos/'
    | '/partos/$id/editar'
    | '/partos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/descartes'
    | '/estacoes'
    | '/prenhezes'
    | '/protocolos'
    | '/relatorios'
    | '/'
    | '/matrizes/$id'
    | '/partos/novo'
    | '/matrizes'
    | '/partos'
    | '/partos/$id/editar'
    | '/partos/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/descartes'
    | '/_app/estacoes'
    | '/_app/prenhezes'
    | '/_app/protocolos'
    | '/_app/relatorios'
    | '/_app/'
    | '/_app/matrizes/$id'
    | '/_app/partos/novo'
    | '/_app/matrizes/'
    | '/_app/partos/'
    | '/_app/partos/$id/editar'
    | '/_app/partos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolos': {
      id: '/_app/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof AppProtocolosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prenhezes': {
      id: '/_app/prenhezes'
      path: '/prenhezes'
      fullPath: '/prenhezes'
      preLoaderRoute: typeof AppPrenhezesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estacoes': {
      id: '/_app/estacoes'
      path: '/estacoes'
      fullPath: '/estacoes'
      preLoaderRoute: typeof AppEstacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/descartes': {
      id: '/_app/descartes'
      path: '/descartes'
      fullPath: '/descartes'
      preLoaderRoute: typeof AppDescartesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/': {
      id: '/_app/partos/'
      path: '/partos'
      fullPath: '/partos/'
      preLoaderRoute: typeof AppPartosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matrizes/': {
      id: '/_app/matrizes/'
      path: '/matrizes'
      fullPath: '/matrizes/'
      preLoaderRoute: typeof AppMatrizesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/novo': {
      id: '/_app/partos/novo'
      path: '/partos/novo'
      fullPath: '/partos/novo'
      preLoaderRoute: typeof AppPartosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matrizes/$id': {
      id: '/_app/matrizes/$id'
      path: '/matrizes/$id'
      fullPath: '/matrizes/$id'
      preLoaderRoute: typeof AppMatrizesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/$id/': {
      id: '/_app/partos/$id/'
      path: '/partos/$id'
      fullPath: '/partos/$id/'
      preLoaderRoute: typeof AppPartosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partos/$id/editar': {
      id: '/_app/partos/$id/editar'
      path: '/partos/$id/editar'
      fullPath: '/partos/$id/editar'
      preLoaderRoute: typeof AppPartosIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDescartesRoute: typeof AppDescartesRoute
  AppEstacoesRoute: typeof AppEstacoesRoute
  AppPrenhezesRoute: typeof AppPrenhezesRoute
  AppProtocolosRoute: typeof AppProtocolosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMatrizesIdRoute: typeof AppMatrizesIdRoute
  AppPartosNovoRoute: typeof AppPartosNovoRoute
  AppMatrizesIndexRoute: typeof AppMatrizesIndexRoute
  AppPartosIndexRoute: typeof AppPartosIndexRoute
  AppPartosIdEditarRoute: typeof AppPartosIdEditarRoute
  AppPartosIdIndexRoute: typeof AppPartosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDescartesRoute: AppDescartesRoute,
  AppEstacoesRoute: AppEstacoesRoute,
  AppPrenhezesRoute: AppPrenhezesRoute,
  AppProtocolosRoute: AppProtocolosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppMatrizesIdRoute: AppMatrizesIdRoute,
  AppPartosNovoRoute: AppPartosNovoRoute,
  AppMatrizesIndexRoute: AppMatrizesIndexRoute,
  AppPartosIndexRoute: AppPartosIndexRoute,
  AppPartosIdEditarRoute: AppPartosIdEditarRoute,
  AppPartosIdIndexRoute: AppPartosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
