ALTER FUNCTION public.registrar_parto(UUID, DATE, TEXT, TEXT, TEXT) SECURITY INVOKER;
ALTER FUNCTION public.registrar_diagnostico(UUID, TEXT, DATE) SECURITY INVOKER;
ALTER FUNCTION public.finalizar_lote(UUID, DATE, TEXT, NUMERIC, NUMERIC, NUMERIC) SECURITY INVOKER;